### ISSUE TITLE
Not able to add point on object constraint in a sketch

### ISSUE THREAD

**Issue by philodi** [Ondsel-Development/OndselSolver#52]
In Ondsel 2024.1.0 (35694) I am not able to add a point on object constraint by pressing O. Nevertheless this shortcut is related to the constraint. Is that constraint not valid in Ondsel? If this is the case: How should someone replace this constraint?

**Comment by PaddleStroke** [comment]
In Ondsel we are using the unified constraint command. So both constraints (coincident and Point on object) are done with the same tool.
So select the point and the line then C.
