### ISSUE TITLE
Compilation error of the FreeCAD OndselSolver submodule in Arch Linux

### ISSUE THREAD

**Issue by marioalexis84** [Ondsel-Development/OndselSolver#60]
To compile on current Arch Linux, the `<algorithm>` header is needed in `FunctionX.cpp` and `SymbolicParser.cpp` files.

**Comment by huguesdpdn-aerospace** [comment]
Confirmed, this error has been fixed with [PR#59](https://github.com/Ondsel-Development/OndselSolver/pull/59)
Tested on my fresh ArchLinux with `gcc 14.2.1`

This issue can be closed
