### ISSUE TITLE
no quantities in BOM

### ISSUE THREAD

**Issue by snelweg** [Ondsel-Development/OndselSolver#61]
Am I missing something here?

Using Ondsel and your WB I make an assembly and would like to make a BOM of the assembly.
Everything works, but the quantities are not calculated.

I think this might be a problem with Ondsel because all the inserted parts get a number added if that part is already in the assembly.
Or do I have to do something special with the part itself like giving it a label in a special way?
![bom](https://github.com/Ondsel-Development/OndselSolver/assets/1257901/a5eeeb2c-d8b5-48d1-8ba9-486111eb44d2)

> 
> OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
>     Word size of Ondsel: 64-bit
>     Version: 2024.2.0.37191 (Git) AppImage
>     Build type: Release
>     Branch: (HEAD detached at 2024.2.0)
>     Hash: 2ad5fb327d068ae6280cf702d528b3a6e35770a7
>     Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
>     Locale: Dutch/Netherlands (nl_NL)

    Installed mods:

    BillOfMaterials 0.0.8.2
    TitleBlock 0.5.2.1
    Ondsel-Lens 2024.5.6.01
[assembly.FCStd.txt](https://github.com/Ondsel-Development/OndselSolver/files/15446998/assembly.FCStd.txt)
[RolKasten.FCStd.txt](https://github.com/Ondsel-Development/OndselSolver/files/15446999/RolKasten.FCStd.txt)

**Comment by PaddleStroke** [comment]
You are using the bill of material workbench. The issue is related to it not to the integrated assembly wb.
From what you are saying I guess the BOM workbench does not handle the case of links. Hence the quantity issue.

I currently have an opened PR to add a BoM tool in assembly : https://github.com/FreeCAD/FreeCAD/pull/14198 which handles quantity of links correctly.

**Comment by snelweg** [comment]
> You are using the bill of material workbench. The issue is related to it not to the integrated assembly wb. From what you are saying I guess the BOM workbench does not handle the case of links. Hence the quantity issue.

You missed the labeling as shown in the spreadsheet. As I wrote:
"I think this might be a problem with Ondsel because all the inserted parts get a number added if that part is already in the assembly." that way ALL parts become unique.
You can see that in the spreadsheet, in the red squares.

**Comment by snelweg** [comment]
So nothing is fixed nor will it be. Nice!

**Comment by PaddleStroke** [comment]
What do you want me to do? You are reporting a bug of 'Bill Of Material Workbench', this is not a bug of assembly WB. Ondsel is not the author of BOM workbench and it is not in FreeCAD main, it's an addon. You are reporting in the wrong place.

**Comment by snelweg** [comment]
> What do you want me to do? You are reporting a bug of 'Bill Of Material Workbench', this is not a bug of assembly WB. Ondsel is not the author of BOM workbench and it is not in FreeCAD main, it's an addon. You are reporting in the wrong 

The problem is that when I insert a part into an assembly the name/label of the part gets a number added. What is  not clear about that? And that happens in the Ondsel WB.
